# Generated by Django 4.0 on 2021-12-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_office_office_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='doctor',
            field=models.ManyToManyField(to='base.Doctor'),
        ),
    ]
