# Generated by Django 4.0 on 2021-12-15 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0004_service_doctor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'permissions': (('can_do_doctor_stuff', "Can view patients, all appointments, medical tests, his patients' personals"),)},
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.RESTRICT, to='auth.user'),
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.RESTRICT, to='auth.user'),
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
            ],
            options={
                'permissions': (('can_do_admin_stuff', 'Register new employees etc.'),),
            },
        ),
    ]
