# Generated by Django 4.0 on 2021-12-15 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_patient_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['full_name'], 'permissions': (('can_do_patient_stuff', ''),)},
        ),
    ]
