# Generated by Django 4.0 on 2021-12-15 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_patient_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['full_name']},
        ),
        migrations.DeleteModel(
            name='Administrator',
        ),
    ]
