# from django.conf.urls import url
from django.urls import re_path
from . import views


urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^signup/$', views.patient_signup, name='patient-signup'),
    re_path(r'^users/$', views.UserListView.as_view(), name='users'),
    re_path(r'^user/create/$', views.UserCreate.as_view(), name='create-user'),
    re_path(r'^user/(?P<pk>\d+)/update/$', views.UserUpdate.as_view(), name='update-user'),
    re_path(r'^services/$', views.ServiceListView.as_view(), name='services'),
    re_path(r'^service/(?P<pk>\d+)$', views.ServiceDetailView.as_view(), name='service-detail'),
    re_path(r'^service/create/$', views.ServiceCreate.as_view(), name='create-service'),
    re_path(r'^service/(?P<pk>\d+)/update/$', views.ServiceUpdate.as_view(), name='update-service'),
    re_path(r'^doctors/$', views.DoctorListView.as_view(), name='doctors'),
    re_path(r'^doctor/create/$', views.DoctorCreate.as_view(), name='create-doctor'),
    re_path(r'^doctor/(?P<pk>\d+)$', views.DoctorDetailView.as_view(), name='doctor-detail'),
    re_path(r'^doctor/(?P<pk>\d+)/update/$', views.DoctorUpdate.as_view(), name='update-doctor'),
    re_path(r'^positions/$', views.PositionListView.as_view(), name='positions'),
    re_path(r'^position/create/$', views.PositionCreate.as_view(), name='create-position'),
    re_path(r'^position/(?P<pk>\d+)/update/$', views.PositionUpdate.as_view(), name='update-position'),
    re_path(r'^specializations/$', views.SpecializationListView.as_view(), name='specializations'),
    re_path(r'^specialization/create/$',
            views.SpecializationCreate.as_view(), name='create-specialization'),
    re_path(r'^specialization/(?P<pk>\d+)/update/$',
            views.SpecializationUpdate.as_view(), name='update-specialization'),
    re_path(r'^patients/$', views.PatientListView.as_view(), name='patients'),
    re_path(r'^patient/(?P<pk>\d+)/personal/$', views.patient_personal, name='patient-personal'),
    re_path(r'^patient/create/$', views.PatientCreate.as_view(), name='create-patient'),
    re_path(r'^patient/(?P<pk>\d+)/update/$', views.PatientUpdate.as_view(), name='update-patient'),
    re_path(r'^employees/$', views.EmployeeListView.as_view(), name='employees'),
    re_path(r'^employee/create/$', views.EmployeeCreate.as_view(), name='create-employee'),
    re_path(r'^employee/(?P<pk>\d+)/update/$', views.EmployeeUpdate.as_view(), name='update-employee'),
    re_path(r'^personal/$', views.personal, name='personal'),
    re_path(r'^personal/appointment/(?P<pk>\d+)/$', views.AppointmentDetailView.as_view(), name='appointment-detail'),
    re_path(r'^personal/appointment/(?P<pk>\d+)/update/$', views.AppointmentUpdate.as_view(), name='update-appointment'),
    re_path(r'^personal/appointment/create/$', views.AppointmentCreate.as_view(), name='create-appointment'),
    re_path(r'^personal/medicaltest/(?P<pk>\d+)/$', views.MedicalTestDetailView.as_view(), name='medicaltest-detail'),
    re_path(r'^personal/medicaltest/(?P<pk>\d+)/update/$', views.MedicalTestUpdate.as_view(), name='update-medicaltest'),
    re_path(r'^personal/medicaltest/create/$', views.MedicalTestCreate.as_view(), name='create-medicaltest'),
]
